'''
Created on Feb8, 2017

@author: bergr

The names defined here are to be used to refer to the main object dict devices and positioners
'''

''' just reusing a name for convienience in simulation here '''
DNM_ENERGY  = "ENERGY"
DNM_DETECTOR_X = "DETECTOR_X"
DNM_DETECTOR_Y = "DETECTOR_Y"
DNM_DETECTOR_Z = "DETECTOR_Z"
DNM_GATE = "Gate"
DNM_SHUTTER = "Shutter"
DNM_COUNTER_APD = "Counter_APD"

#######
DNM_PFIL1607_5_I10_01 = "PFIL1607_5_I10_01"
DNM_PFIL1607_5_I10_02 =  "PFIL1607_5_I10_02"
                                                                        
DNM_IMAG_M1_VERT_PandR_IN_UP = "IMAG_M1_VERT_PandR_IN_UP"
DNM_IMAG_M1_VERT_PandR_OUT_UP = "IMAG_M1_VERT_PandR_OUT_UP"
DNM_IMAG_M1_VERT_PandR_DOWN = "IMAG_M1_VERT_PandR_DOWN"
DNM_IMAG_M1_HORZ_STRIPE_SEL = "IMAG_M1_HORZ_STRIPE_SEL"
DNM_IMAG_M1_YAW = "IMAG_M1_YAW"
DNM_IMAG_M1_BENDER_UPSTREAM = "IMAG_M1_BENDER_UPSTREAM"
DNM_IMAG_M1_BENDER_DOWNSTREAM = "IMAG_M1_BENDER_DOWNSTREAM"
                                                                        
DNM_IMAG_M2_VERT_PandR_IN_UP = "IMAG_M2_VERT_PandR_IN_UP"
DNM_IMAG_M2_VERT_PandR_OUT_UP = "IMAG_M2_VERT_PandR_OUT_UP"
DNM_IMAG_M2_VERT_PandR_DOWN = "IMAG_M2_VERT_PandR_DOWN"
DNM_IMAG_M2_HORZ_STRIPE_SEL = "IMAG_M2_HORZ_STRIPE_SEL"
DNM_IMAG_M2_YAW = "IMAG_M2_YAW"
DNM_IMAG_M2_BENDER_UPSTREAM = "IMAG_M2_BENDER_UPSTREAM"
DNM_IMAG_M2_BENDER_DOWNSTREAM = "IMAG_M2_BENDER_DOWNSTREAM"
DNM_IMAG_MONO_BRAGG = "IMAG_MONO_BRAGG"
                                                                        
DNM_IMAG_VM_UPPER_BLADE = "IMAG_VM_UPPER_BLADE"
DNM_IMAG_VM_LOWER_BLADE = "IMAG_VM_LOWER_BLADE"
DNM_IMAG_MONO_CRYSTAL_2_Z2 = "IMAG_MONO_CRYSTAL_2_Z2"
DNM_IMAG_MONO_CRYSTAL_2_Y2 = "IMAG_MONO_CRYSTAL_2_Y2"
DNM_IMAG_MONO_CRYSTAL_2_Theta2 = "IMAG_MONO_CRYSTAL_2_Theta2"
DNM_IMAG_MONO_CRYSTAL_2_CHI_2 = "IMAG_MONO_CRYSTAL_2_CHI_2"
DNM_IMAG_MONO_TABLE_VERT_Y = "IMAG_MONO_TABLE_VERT_Y"
DNM_IMAG_MONO_TABLE_HORZ_X = "IMAG_MONO_TABLE_HORZ_X"
                                                                  
DNM_IMAG_TABLE_VERTICAL_1 = "IMAG_TABLE_VERTICAL_1"
DNM_IMAG_TABLE_VERTICAL_2 = "IMAG_TABLE_VERTICAL_2"
DNM_IMAG_TABLE_VERTICAL_3 = "IMAG_TABLE_VERTICAL_3"
DNM_IMAG_TABLE_HORIZONTAL_1 = "IMAG_TABLE_HORIZONTAL_1"
DNM_IMAG_TABLE_HORIZONTAL_2 = "IMAG_TABLE_HORIZONTAL_2"
                                                                  
DNM_IMAG_JJ_SLIT_US_VERT_GAP = "IMAG_JJ_SLIT_US_VERT_GAP"
DNM_IMAG_JJ_SLIT_US_VERT_CENTER = "IMAG_JJ_SLIT_US_VERT_CENTER"
DNM_IMAG_JJ_SLIT_US_HOR_GAP = "IMAG_JJ_SLIT_US_HOR_GAP"
DNM_IMAG_JJ_SLIT_US_HOR_CENTER = "IMAG_JJ_SLIT_US_HOR_CENTER"
DNM_IMAG_HORIZ_KB_BENDER_1 = "IMAG_HORIZ_KB_BENDER_1"
DNM_IMAG_HORIZ_KB_BENDER_2 = "IMAG_HORIZ_KB_BENDER_2"
DNM_IMAG_HORIZ_KB_VERTICAL = "IMAG_HORIZ_KB_VERTICAL"
DNM_IMAG_HORIZ_KB_TILT = "IMAG_HORIZ_KB_TILT"
                                                                  
DNM_IMAG_VERT_KB_BENDER_1 = "IMAG_VERT_KB_BENDER_1"
DNM_IMAG_VERT_KB_BENDER_2 = "IMAG_VERT_KB_BENDER_2"
DNM_IMAG_VERT_KB_VERTICAL = "IMAG_VERT_KB_VERTICAL"
DNM_IMAG_VERT_KB_TILT = "IMAG_VERT_KB_TILT"
DNM_IMAG_DETECTOR_1_VERTICAL = "IMAG_DETECTOR_1_VERTICAL"
DNM_IMAG_DETECTOR_1_LATERAL  = "IMAG_DETECTOR_1_LATERAL"
DNM_IMAG_DETECTOR_2_VERTICAL = "IMAG_DETECTOR_2_VERTICAL"
DNM_IMAG_DETECTOR_2_LATERAL  = "IMAG_DETECTOR_2_LATERAL"
                                                                  
DNM_IMAG_SAMPLE_ROTARY_STAGE = "IMAG_SAMPLE_ROTARY_STAGE"
DNM_IMAG_ZONE_PLATE_X = "IMAG_ZONE_PLATE_X"
DNM_IMAG_ZONE_PLATE_Y = "IMAG_ZONE_PLATE_Y"
DNM_IMAG_ZONE_PLATE_Z = "IMAG_ZONE_PLATE_Z"
DNM_IMAG_ZONE_PLATE_PITCH = "IMAG_ZONE_PLATE_PITCH"
DNM_IMAG_ZONE_PLATE_YAW = "IMAG_ZONE_PLATE_YAW"
DNM_IMAG_OPTICAL_SAMPLE_VERT = "IMAG_OPTICAL_SAMPLE_VERT"
                                                                  
DNM_IMAG_JJ_SLIT_DS_VERT_GAP = "IMAG_JJ_SLIT_DS_VERT_GAP"
DNM_IMAG_JJ_SLIT_DS_VERT_CENTER = "IMAG_JJ_SLIT_DS_VERT_CENTER"
DNM_IMAG_JJ_SLIT_DS_HOR_GAP = "IMAG_JJ_SLIT_DS_HOR_GAP"
DNM_IMAG_JJ_SLIT_DS_HOR_CENTER = "IMAG_JJ_SLIT_DS_HOR_CENTER"
DNM_IMAG_MACRO_STAGE_UP_DOWN = "IMAG_MACRO_STAGE_UP_DOWN"
DNM_IMAG_MACRO_STAGE_HORIZ = "IMAG_MACRO_STAGE_HORIZ"
DNM_IMAG_MACRO_STAGE_VERT = "IMAG_MACRO_STAGE_VERT"
DNM_IMAG_VISUALIZATION_VERT = "IMAG_VISUALIZATION_VERT"
