'''
Created on Jan 11, 2019

@author: bergr

The names defined here are to be used to refer to the main object dict devices and positioners
'''

DNM_FINE_X = 'FineX'
DNM_FINE_Y = 'FineY'
DNM_FINE_ZX = 'FineZX'
DNM_FINE_ZY = 'FineZY'

DNM_SAMPLE_FINE_X = 'SampleFineX'
DNM_SAMPLE_FINE_Y = 'SampleFineY'
DNM_COARSE_X = 'Coarse.X'
DNM_COARSE_Y = 'Coarse.Y'
DNM_COARSE_Z = 'Coarse.Z'
DNM_OSA_X = 'OSA.X'
DNM_OSA_Y = 'OSA.Y'
DNM_OSA_Z = 'OSA.Z'
DNM_OSA_Z_BASE = '_OSAZ_base'
DNM_DETECTOR_X = 'Detector.X'
DNM_DETECTOR_Y = 'Detector.Y'
DNM_DETECTOR_Z = 'Detector.Z'
DNM_ZONEPLATE_X = 'ZonePlate.X'
DNM_ZONEPLATE_Y = 'ZonePlate.Y'
DNM_ZONEPLATE_Z = 'ZonePlate.Z'
DNM_ZONEPLATE_Z_BASE = '_ZonePlateZ_base'
DNM_ZONEPLATE_SCAN_MODE = 'Zpz_scanModeFlag'
DNM_ZONEPLATE_INOUT = 'Zpz_inout'
DNM_ZONEPLATE_INOUT_FBK = 'Zpz_inout_fbk'
DNM_ZONEPLATE_Z_ADJUST = 'Zpz_adjust'
DNM_SAMPLE_X = 'SampleX'
DNM_SAMPLE_Y = 'SampleY'

DNM_E712_OPHYD_DEV = 'E712OphydDev'
DNM_E712_WIDGET = 'E712ControlWidget'

DNM_GONI_X = 'GoniX'
DNM_GONI_Y = 'GoniY'
DNM_GONI_Z = 'GoniZ'
DNM_GONI_THETA = 'GoniTheta'
DNM_ENERGY = 'ENERGY'
DNM_SLIT_X = 'SlitX'
DNM_SLIT_Y = 'SlitY'
DNM_M3_PITCH = 'M3STXMPitch'
DNM_EPU_GAP = 'EPUGap'
DNM_EPU_OFFSET = 'EPUOffset'
DNM_EPU_HARMONIC = 'EPUHarmonic'
DNM_EPU_POLARIZATION = 'EPUPolarization'
DNM_EPU_ANGLE = 'EPUAngle'

DNM_SHUTTER = 'Shutter'
DNM_GATE = 'Gate'
DNM_COUNTER_APD = 'Counter_APD'
DNM_PMT = 'PMT'
DNM_DEFAULT_COUNTER = 'counter0'

DNM_OSAX_TRACKING = 'OX_tracking_enabled'
DNM_OSAY_TRACKING = 'OY_tracking_enabled'
DNM_OSAZ_TRACKING = 'OZ_tracking_enabled'

DNM_BEAM_DEFOCUS = 'Beam_Defocus'

DNM_RING_CURRENT = 'StorageRingCurrent'
DNM_TYCHO_CAMERA = 'tycho_camera'

DNM_CALIB_CAMERA_SRVR = 'Calib_camera_server'
DNM_CALIB_CAMERA_CLIENT = 'Calib_camera_client'

DNM_GATAN_ROD_TEMP_FBK = 'GatanRodTemp'

DNM_AX1_INTERFER_VOLTS = 'Axis1_Interfer_Volts'
DNM_AX2_INTERFER_VOLTS = 'Axis2_Interfer_Volts'

DNM_SHUTTERTASKRUN		= 'ShutterTaskRun'
DNM_DETCNTR_SNAPSHOT  = 'DetCntr_Snapshot'
DNM_OSACNTR_SNAPSHOT  = 'OsaCntr_Snapshot'
DNM_IDEAL_A0          = 'Ideal_A0'
DNM_CALCD_ZPZ         = 'Calcd_Zpz'
DNM_ZPZ_ADJUST        = 'Zpz_adjust'
DNM_DELTA_A0          = 'Delta_A0'
DNM_FOCAL_LENGTH      = 'Focal_Length'
DNM_A0                = 'A0'
DNM_A0MAX             = 'A0Max'
DNM_A0FORCALC         = 'A0ForCalc'
DNM_ZPZ_POS           = 'Zpz_pos'
DNM_ZP_DEF            = 'Zp_def'
DNM_OSA_DEF           = 'OSA_def'
DNM_ZP_SELECT         = 'Zp_select'
DNM_OSA_SELECT        = 'OSA_select'
DNM_ENERGY_ENABLE     = 'Energy_enable'
DNM_ENERGY_RBV        = 'ENERGY_RBV'
DNM_ZPZ_RBV           = 'ZPZ_RBV'
DNM_ZP_DEF_A          = 'Zp_def_A'
DNM_ZP_DEF1_A         = 'Zp_def1_A'
DNM_ZP_DEF2_A         = 'Zp_def2_A'
DNM_ZP_DEF3_A         = 'Zp_def3_A'
DNM_ZP_DEF4_A         = 'Zp_def4_A'
DNM_ZP_DEF5_A         = 'Zp_def5_A'
DNM_ZP_DEF6_A         = 'Zp_def6_A'
DNM_ZP_DEF7_A         = 'Zp_def7_A'
DNM_SRSTATUS_SHUTTERS = 'SRStatus_shutters'
DNM_EPU_POL_FBK       = 'Epu_pol_fbk'
DNM_EPU_POL_ANGLE     = 'Epu_pol_angle'
DNM_EPU_GAP_FBK       = 'Epu_gap_fbk'
DNM_EPU_GAP_OFFSET    = 'Epu_gap_offset'
DNM_EPU_HARMONIC_PV      = 'Epu_harmonic'
DNM_SYSTEM_MODE_FBK   = 'SYSTEM:mode:fbk'
DNM_TICKER            = 'ticker'
DNM_CX_AUTO_DISABLE_POWER = 'CX_auto_disable_power'
DNM_CY_AUTO_DISABLE_POWER = 'CY_auto_disable_power'
DNM_DX_AUTO_DISABLE_POWER = 'DX_auto_disable_power'
DNM_DY_AUTO_DISABLE_POWER = 'DY_auto_disable_power'
DNM_ACCRANGE  = 'accRange'
DNM_FX_FORCE_DONE = 'FX_force_done'
DNM_FY_FORCE_DONE = 'FY_force_done'
DNM_OX_FORCE_DONE = 'OX_force_done'
DNM_OY_FORCE_DONE = 'OY_force_done'
DNM_OSAXYZ_LOCKPOSITION_ENABLED = 'OSAXYZ_lockposition_enabled'
DNM_OSAXY_GOTO_LOCKPOSITION = 'OSAXY_goto_lockposition'
DNM_OSAZ_GOTO_LOCKPOSITION  = 'OSAZ_goto_lockposition'
DNM_SET_XY_LOCKPOSITION     = 'Set_XY_lockposition'
DNM_SET_Z_LOCKPOSITION      = 'Set_Z_lockposition'
DNM_MONO_EV_FBK             = 'Mono_ev_fbk'
DNM_MONO_GRATING_FBK        = 'Mono_grating_fbk'

