
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-09-05T11:02:19-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "18f09d4dbde6228fe381b367eef26d0fd1dc19b9",
 "version": "1.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
