
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-04T11:54:09-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c5d55210e0676a37a9d0468c75fc7e0fa6454dbc",
 "version": "0.post1+gc5d5521"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
